### ISSUE TITLE
Symbolic execution failures with red-black-tree example

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#125]
1.  Check out https://github.com/agroce/rb_tree_demo
2.  build (just make all)

angr fails thus:

```
$ deepstate-angr ./ds_rb
WARNING | 2018-11-19 20:20:32,440 | angr.state_plugins.unicorn_engine | failed loading "angr_native.so", unicorn support disabled (/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/lib/angr_native.so: cannot open shared object file: No such file or directory: /usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/lib/angr_native.so: cannot open shared object file: No such file or directory)
WARNING | 2018-11-19 20:20:32,968 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
CRITICAL | 2018-11-19 20:21:02,607 | deepstate.angr | Execution never hit `DeepState_Setup` in binary `./ds_rb`
```

Manticore does this:

```
$ deepstate-manticore ./ds_rb
2018-11-19 20:27:37,880: [27214] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 443, in run
    current_state = self._workspace.load_state(current_state_id)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/workspace.py", line 386, in load_state
    return self._store.load_state('{}{:08x}{}'.format(self._prefix, state_id, self._suffix), delete=delete)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/workspace.py", line 165, in load_state
    state = self._serializer.deserialize(f)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/workspace.py", line 53, in deserialize
    return cPickle.load(f)
MemoryError

2018-11-19 20:27:37,882: [27214] m.manticore:INFO: Results in /home/vagrant/rb_tree_demo/mcore_IRiX4f
2018-11-19 20:27:37,883: [27214] m.manticore:INFO: Total time: 3.23009586334
```

**Comment by agroce** [comment]
libFuzzer works fine with leak detection off (right now nodes can fail to be freed, need to investigate that)

**Comment by ggrieco-tob** [comment]
Can you re-try with the latest release? (that will use updated version of manticore and angr).

**Comment by agroce** [comment]
manticore has the instruction complaint, angr seems fine now
