### ISSUE TITLE
Reducer requires manticore

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#136]
DeepState is now quite usable without manticore/angr (e.g. on Mac) as a fuzzer front end.  But the reducer is configured to fail if manticore isn't present:

```
deepstate-reduce ./ds_rb fails/01daf2cba12222cfb51e32747b1ed143a7e18f0c.fail small.fail
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/deepstate-reduce", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'manticore==0.1.10' distribution was not found and is required by deepstate
```

**Comment by agroce** [comment]
Actually, getting manticore with a satisfying version is easy, even if it doesn't work.  Angr, on the other hand, fails on my mac, due to some dependency issues.  Is there a way in Python to try to install both when we install, but not require them for running deepstate tools?  It's easy to imagine at some point one or the other tool is currently broken due to deps, and people wanting to proceed with the working one, for example...

**Comment by agroce** [comment]
Fixed in commit https://github.com/trailofbits/deepstate/commit/18e8761576c059b760d25cebe19a93bb728835bd

**Comment by agroce** [comment]
(I just made them conditional dependencies for now -- since on macOS if you want to use angr/manticore you are doing cross-compiles, I figure you can figure out to install them yourself)
