### ISSUE TITLE
StreamingAndFormatting fails in angr and manticore

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/deepstate#173]
I think @pgoodman had some experience fixing a bug in formatting. Here is the log:

```
================================================================================
RUNNING: deepstate-angr build/examples/StreamingAndFormatting
WARNING | 2019-04-21 22:02:44,618 | angr.state_plugins.symbolic_memory | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2019-04-21 22:02:44,618 | angr.state_plugins.symbolic_memory | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2019-04-21 22:02:44,619 | angr.state_plugins.symbolic_memory | 1) setting a value to the initial state
WARNING | 2019-04-21 22:02:44,619 | angr.state_plugins.symbolic_memory | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2019-04-21 22:02:44,619 | angr.state_plugins.symbolic_memory | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY_REGISTERS}, to suppress these messages.
WARNING | 2019-04-21 22:02:44,619 | angr.state_plugins.symbolic_memory | Filling register r13 with 8 unconstrained bytes referenced from 0x416ad0 (__libc_start_main+0x0 in StreamingAndFormatting (0x416ad0))
WARNING | 2019-04-21 22:02:44,621 | angr.state_plugins.symbolic_memory | Filling register r12 with 8 unconstrained bytes referenced from 0x416ad2 (__libc_start_main+0x2 in StreamingAndFormatting (0x416ad2))
WARNING | 2019-04-21 22:02:44,625 | angr.state_plugins.symbolic_memory | Filling register rbx with 8 unconstrained bytes referenced from 0x416ad8 (__libc_start_main+0x8 in StreamingAndFormatting (0x416ad8))
WARNING | 2019-04-21 22:02:44,750 | angr.state_plugins.symbolic_memory | Filling register r14 with 8 unconstrained bytes referenced from 0x4162e0 (generic_start_main+0x0 in StreamingAndFormatting (0x4162e0))
WARNING | 2019-04-21 22:02:44,805 | angr.state_plugins.symbolic_memory | Filling register r15 with 8 unconstrained bytes referenced from 0x441f5a (_dl_aux_init+0x1a in StreamingAndFormatting (0x441f5a))
WARNING | 2019-04-21 22:02:45,738 | angr.state_plugins.symbolic_memory | Filling register cc_ndep with 8 unconstrained bytes referenced from 0x4402f5 (__sbrk+0x25 in StreamingAndFormatting (0x4402f5))
INFO    | 2019-04-21 22:03:23,602 | deepstate.angr | Running 3 tests across 1 workers
TRACE   | 2019-04-21 22:03:31,213 | deepstate | Running Streaming_BasicLevels from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(19)
DEBUG   | 2019-04-21 22:03:31,213 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(20): This is a debug message
TRACE   | 2019-04-21 22:03:31,213 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(21): This is a trace message
INFO    | 2019-04-21 22:03:31,214 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(22): This is an info message
WARNING | 2019-04-21 22:03:31,214 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(23): This is a warning message
ERROR   | 2019-04-21 22:03:31,214 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(24): This is a error message
TRACE   | 2019-04-21 22:03:31,215 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(25): This is a trace message again
ERROR   | 2019-04-21 22:03:31,215 | deepstate | Failed: Streaming_BasicLevels
TRACE   | 2019-04-21 22:03:31,215 | deepstate | Input: 
TRACE   | 2019-04-21 22:03:37,916 | deepstate | Running Streaming_BasicTypes from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(29)
TRACE   | 2019-04-21 22:03:37,917 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(30): 97
TRACE   | 2019-04-21 22:03:37,917 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(31): 1
TRACE   | 2019-04-21 22:03:37,918 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(32): 1.000000
TRACE   | 2019-04-21 22:03:37,918 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(33): string
TRACE   | 2019-04-21 22:03:37,918 | deepstate | /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(34): 0x0000000000000000
TRACE   | 2019-04-21 22:03:37,918 | deepstate | Passed: Streaming_BasicTypes
TRACE   | 2019-04-21 22:03:37,918 | deepstate | Input: 
WARNING | 2019-04-21 22:03:40,727 | angr.state_plugins.symbolic_memory | Filling register xmm6 with 16 unconstrained bytes referenced from 0x4044d6 (__printf_chk+0x46 in StreamingAndFormatting (0x4044d6))
WARNING | 2019-04-21 22:03:40,731 | angr.state_plugins.symbolic_memory | Filling register xmm7 with 16 unconstrained bytes referenced from 0x4044de (__printf_chk+0x4e in StreamingAndFormatting (0x4044de))
TRACE   | 2019-04-21 22:03:45,026 | deepstate | Running Formatting_OverridePrintf from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(37)
ERROR   | 2019-04-21 22:03:45,028 | deepstate.angr | Uncaught exception: %c requires int or char
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_angr.py", line 313, in run_test
    do_run_test(project, test, apis, run_state, should_call_state)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_angr.py", line 303, in do_run_test
    DeepAngr(state=state).report()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 410, in report
    logger(self._stream_to_message(stream))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 346, in _stream_to_message
    message.append(format_str % val)
TypeError: %c requires int or char
DONE
TOTAL EXECUTION TIME: 62.667269229888916
RETURN VALUE: 0
RETURNING AS RESULT: EXCEPTION RAISED
================================================================================
F
================================================================================
RUNNING: deepstate-manticore build/examples/StreamingAndFormatting
2019-04-21 22:03:48,603: [5280] m.c.manticore:INFO: Verbosity set to 1.
INFO:deepstate.mcore:Running 3 tests across 1 workers
2019-04-21 22:03:53,342: [5280] m.c.manticore:INFO: Verbosity set to 1.
TRACE:deepstate:Running Streaming_BasicLevels from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(19)
DEBUG:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(20): This is a debug message
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(21): This is a trace message
INFO:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(22): This is an info message
WARNING:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(23): This is a warning message
ERROR:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(24): This is a error message
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(25): This is a trace message again
ERROR:deepstate:Failed: Streaming_BasicLevels
TRACE:deepstate:Input: 
2019-04-21 22:03:55,090: [5280] m.c.manticore:INFO: Results in /home/travis/build/trailofbits/deepstate/mcore_0cdauwfh
2019-04-21 22:03:55,090: [5280] m.c.manticore:INFO: Total time: 1.5052685737609863
2019-04-21 22:03:55,126: [5280] m.c.manticore:INFO: Verbosity set to 1.
TRACE:deepstate:Running Streaming_BasicTypes from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(29)
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(30): 97
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(31): 1
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(32): 1.000000
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(33): string
TRACE:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(34): 0x0000000000000000
TRACE:deepstate:Passed: Streaming_BasicTypes
TRACE:deepstate:Input: 
2019-04-21 22:03:56,853: [5280] m.c.manticore:INFO: Results in /home/travis/build/trailofbits/deepstate/mcore_3tvnc1c0
2019-04-21 22:03:56,853: [5280] m.c.manticore:INFO: Total time: 1.4543237686157227
2019-04-21 22:03:56,889: [5280] m.c.manticore:INFO: Verbosity set to 1.
2019-04-21 22:03:57,378: [5280] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00000000004019ec:	66 0f 28 d0	movapd	xmm2, xmm0
2019-04-21 22:03:57,384: [5280] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00000000004019f5:	66 0f 28 c8	movapd	xmm1, xmm0
TRACE:deepstate:Running Formatting_OverridePrintf from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(37)
2019-04-21 22:03:58,865: [5280] m.c.executor:ERROR: Exception: %c requires int or char
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/executor.py", line 454, in run
    if not current_state.execute():
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/state.py", line 18, in execute
    result = self._platform.execute()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/platforms/linux.py", line 2284, in execute
    self.current.execute()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 912, in execute
    self._publish('will_execute_instruction', self.PC, insn)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 127, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 142, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 135, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/manticore.py", line 150, in _hook_callback
    cb(state)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 258, in <lambda>
    return lambda state: state.invoke_model(func)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/state.py", line 69, in invoke_model
    self._platform.invoke_model(model, prefix_args=(self,))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/platforms/platform.py", line 36, in invoke_model
    self._function_abi.invoke(model, prefix_args)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 358, in invoke
    result = model(*arguments)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 198, in hook_Pass
    DeepManticore(state).api_pass()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 525, in api_pass
    self.pass_test()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 140, in pass_test
    raise TerminateState(OUR_TERMINATION_REASON, testcase=False)
manticore.core.state.TerminateState: I DeepState'd it
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/executor.py", line 471, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 127, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 135, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 312, in done_test
    mc.report()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 410, in report
    logger(self._stream_to_message(stream))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 346, in _stream_to_message
    message.append(format_str % val)
TypeError: %c requires int or char
ERROR:deepstate.mcore:State 0 terminated due to internal error: %c requires int or char
TRACE:deepstate:Running Formatting_OverridePrintf from /home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(37)
ERROR:deepstate.mcore:Uncaught exception: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/executor.py", line 454, in run
    if not current_state.execute():
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/state.py", line 18, in execute
    result = self._platform.execute()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/platforms/linux.py", line 2284, in execute
    self.current.execute()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 912, in execute
    self._publish('will_execute_instruction', self.PC, insn)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 127, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 142, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 135, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/manticore.py", line 150, in _hook_callback
    cb(state)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 258, in <lambda>
    return lambda state: state.invoke_model(func)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/state.py", line 69, in invoke_model
    self._platform.invoke_model(model, prefix_args=(self,))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/platforms/platform.py", line 36, in invoke_model
    self._function_abi.invoke(model, prefix_args)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 358, in invoke
    result = model(*arguments)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 198, in hook_Pass
    DeepManticore(state).api_pass()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 525, in api_pass
    self.pass_test()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 140, in pass_test
    raise TerminateState(OUR_TERMINATION_REASON, testcase=False)
manticore.core.state.TerminateState: I DeepState'd it
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/executor.py", line 471, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 127, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 135, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 312, in done_test
    mc.report()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 410, in report
    logger(self._stream_to_message(stream))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 346, in _stream_to_message
    message.append(format_str % val)
TypeError: %c requires int or char
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 374, in run_test
    do_run_test(state, apis, test, hook_test)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 369, in do_run_test
    m.run(procs=1)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/manticore.py", line 436, in run
    self._start_workers(procs, profiling=should_profile)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/manticore.py", line 281, in _start_workers
    target()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/core/executor.py", line 497, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 127, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 144, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/manticore/utils/event.py", line 135, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 312, in done_test
    mc.report()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 410, in report
    logger(self._stream_to_message(stream))
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 346, in _stream_to_message
    message.append(format_str % val)
TypeError: %c requires int or char
DONE
TOTAL EXECUTION TIME: 13.747435569763184
RETURN VALUE: 0
RETURNING AS RESULT: INTERNAL ERROR
================================================================================
F
======================================================================
FAIL: test_angr (test_streamingandformatting.StreamingAndFormattingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/trailofbits/deepstate/tests/deepstate_base.py", line 7, in test_angr
    self.run_deepstate("deepstate-angr")
  File "/home/travis/build/trailofbits/deepstate/tests/test_streamingandformatting.py", line 10, in run_deepstate
    self.assertEqual(r, 0)
AssertionError: 'EXCEPTION RAISED' != 0
======================================================================
FAIL: test_manticore (test_streamingandformatting.StreamingAndFormattingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/trailofbits/deepstate/tests/deepstate_base.py", line 10, in test_manticore
    self.run_deepstate("deepstate-manticore")
  File "/home/travis/build/trailofbits/deepstate/tests/test_streamingandformatting.py", line 10, in run_deepstate
    self.assertEqual(r, 0)
AssertionError: 'INTERNAL ERROR' != 0
----------------------------------------------------------------------
Ran 2 tests in 76.423s
```

**Comment by GrosQuildu** [comment]
Fixed in #326 (https://github.com/trailofbits/deepstate/pull/326/commits/286e4da5f1330c6465ab281e1e432b889d34f067). Closing.
