### ISSUE TITLE
Symbolic execution interfaces have a problem with doubles

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#245]
```
#include <deepstate/DeepState.hpp>

using namespace deepstate;

TEST(A, B) {
  double x;
  DeepState_SymbolizeData(&x, &x + (sizeof(x)-1));

  ASSERT (x == ((x+1)-1)) << x << " != " << (x+1)-1;
}
```

produces:

```
INFO    | 2019-10-12 17:34:18,153 | deepstate.angr | Running 1 tests across 1 workers
ERROR   | 2019-10-12 17:35:23,619 | deepstate.angr | Uncaught exception: unpack requires a buffer of 0 bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_angr.py", line 316, in run_test
    do_run_test(project, test, apis, run_state, should_call_state)
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_angr.py", line 306, in do_run_test
    DeepAngr(state=state).report()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 414, in report
    logger(self._stream_to_message(stream))
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 336, in _stream_to_message
    val = struct.unpack(unpack_str, data)[0]
struct.error: unpack requires a buffer of 0 bytes
```

but switching type to int, it works (though produces no interesting tests, which may also bear investigation)

**Comment by agroce** [comment]
Manticore too:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/native/state.py", line 29, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/platforms/linux.py", line 2401, in execute
    self.current.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/native/cpu/abstractcpu.py", line 964, in execute
    self._publish("will_execute_instruction", self.PC, insn)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 145, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 162, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 162, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 160, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 153, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/native/manticore.py", line 259, in _hook_callback
    cb(state)
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 265, in <lambda>
    return lambda state: state.invoke_model(func)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/native/state.py", line 74, in invoke_model
    self._platform.invoke_model(model, prefix_args=(self,))
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/platforms/platform.py", line 53, in invoke_model
    self._function_abi.invoke(model, prefix_args)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/native/cpu/abstractcpu.py", line 367, in invoke
    result = model(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 205, in hook_Pass
    DeepManticore(state).api_pass()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 529, in api_pass
    self.pass_test()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 147, in pass_test
    raise TerminateState(OUR_TERMINATION_REASON, testcase=False)
manticore.core.state.TerminateState: I DeepState'd it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/core/worker.py", line 148, in run
    m._publish("will_terminate_state", current_state, exc)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 145, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore-0.3.1-py3.6.egg/manticore/utils/event.py", line 153, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/main_manticore.py", line 319, in done_test
    mc.report()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 414, in report
    logger(self._stream_to_message(stream))
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/common.py", line 336, in _stream_to_message
    val = struct.unpack(unpack_str, data)[0]
struct.error: unpack requires a buffer of 0 bytes
```

**Comment by agroce** [comment]
Fixed (I think) with https://github.com/trailofbits/deepstate/commit/ced93eed7c1643b20dbe829be5679e136cbecf3a
