### ISSUE TITLE
Front-end for Eclipser broken

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#262]
```
Successfully built 20b8ab81e605
Successfully tagged deepstate_new:latest
cmp3149:deepstate adg326$ docker run -it deepstate_new
user@162d446921ab:~$ cd deepstate/build/examples/
user@162d446921ab:~/deepstate/build/examples$ deepstate-eclipser Runlen 
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-eclipser", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-eclipser')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/eclipser.py", line 136, in main
    fuzzer = Eclipser(envvar="ECLIPSER_HOME")
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/frontend.py", line 75, in __init__
    raise FrontendError(f"${envvar} does not contain supplied fuzzer executable for `{self.FUZZER}`.")
deepstate.frontend.frontend.FrontendError: $ECLIPSER_HOME does not contain supplied fuzzer executable for `Eclipser.dll`.
```

**Comment by agroce** [comment]
it's not just that it should be set to build:
```
user@162d446921ab:~/deepstate/build/examples$ export ECLIPSER_HOME=/home/user/Eclipser/build
user@162d446921ab:~/deepstate/build/examples$ echo $ECLIPSER_HOME
/home/user/Eclipser/build
user@162d446921ab:~/deepstate/build/examples$ deepstate-eclipser Runlen 
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-eclipser", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-eclipser')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/eclipser.py", line 139, in main
    fuzzer.parse_args()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/frontend.py", line 170, in parse_args
    parser.add_argument("-o", "--output_test_dir", type=str, default="{}_out".format(str(cls())), help="Directory where tests will be saved.")
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/frontend.py", line 75, in __init__
    raise FrontendError(f"${envvar} does not contain supplied fuzzer executable for `{self.FUZZER}`.")
deepstate.frontend.frontend.FrontendError: $PATH does not contain supplied fuzzer executable for `Eclipser.dll`.
```

**Comment by agroce** [comment]
Fixed in https://github.com/trailofbits/deepstate/pull/263
