### ISSUE TITLE
deepstate-eclipser fails to decode tests in docker image

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#266]
```
[00:00:59:55] Done, clean up and exit...
write_stdin: Bad file descriptor
INFO:deepstate.frontend:Fuzzer subprocess exited with `255`
INFO:deepstate.frontend:Fuzzer subprocess exited with `255`
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-eclipser", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-eclipser')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/eclipser.py", line 143, in main
    fuzzer.run(compiler="dotnet")
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/frontend/frontend.py", line 383, in run
    raise FrontendError(f"{self.fuzzer} run interrupted with non-zero return status. Error: {err.decode('utf-8')}")
AttributeError: 'NoneType' object has no attribute 'decode'
```

Command line was: `deepstate-eclipser ./ds_rb -i AFL_out/queue/`

(after running AFL on the rbtree example)

**Comment by agroce** [comment]
@ex0dus-0x any guess what's going on here?

**Comment by agroce** [comment]
The undecoded tests look ok, but the decode doesn't happen.  I think this is part of the last refactor.  We need some CI for the front-ends, I think...

**Comment by agroce** [comment]
Probably spurious, but did reveal other issue...
