### ISSUE TITLE
Reorg broke front-ends

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#276]
In latest docker build:

```
~/deepstate/build/examples$ deepstate-eclipser ./OneOf 
INFO:deepstate.frontend:Calling pre_exec before fuzzing
Creating output directory.
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-eclipser", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-eclipser')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/fuzz/eclipser.py", line 142, in main
    fuzzer.run(compiler="dotnet")
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/frontend/fuzz.py", line 396, in run
    command = [self.fuzzer] + DeepStateFrontend._dict_to_cmd(self.cmd)
NameError: name 'DeepStateFrontend' is not defined
```

deepstate-X never works now.

**Comment by agroce** [comment]
(fuzzer front-ends only, that is:  deepstate-manticore is still fine, as is deepstate-reduce; but the interfaces inheriting from Frontend are broken
