### ISSUE TITLE
Fix AFL input dir existence check to allow resuming a run

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#286]
```
deepstate-afl ./testcblosc2_AFL -i - --output_test_dir AFL_new_dirty --dirty_mode
INFO:deepstate.frontend:Calling pre_exec before fuzzing
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-afl", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-afl')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/fuzz/afl.py", line 216, in main
    fuzzer.run()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/frontend/fuzz.py", line 392, in run
    self.pre_exec()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/fuzz/afl.py", line 94, in pre_exec
    raise FuzzFrontendError("Seed path doesn't exist. Creating empty seed directory and exiting.")
deepstate.core.frontend.fuzz.FuzzFrontendError: Seed path doesn't exist. Creating empty seed directory and exiting.
```

just turn off the check if passing in `-`

**Comment by agroce** [comment]
Fixed in https://github.com/trailofbits/deepstate/commit/a5a8cf8138ee2ddf9b0030946a96078b373c2c46
