### ISSUE TITLE
Formatting bug

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/deepstate#34]
```ERROR   | 2018-02-18 05:24:10,988 | deepstate.angr | Uncaught exception: unsupported format character 'p' (0x70) at index 1
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 297, in run_test
    do_run_test(project, test, apis, run_state)
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 287, in do_run_test
    DeepAngr(state=state).report()
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 365, in report
    logger(self._stream_to_message(stream))
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 309, in _stream_to_message
    message.append(format_str % val)
ValueError: unsupported format character 'p' (0x70) at index 1
```

We can probably convert this into a `%x` on the Python side.

**Comment by ranweiler** [comment]
@pgoodman, could you point me at how to trigger this?

**Comment by pgoodman** [comment]
```c++
TEST(a, b) {
  printf("%p\n", nullptr);
}```

**Comment by agroce** [comment]
Did #74 fix generally handle this?

**Comment by pgoodman** [comment]
I think so.
