### ISSUE TITLE
Adding --fuzzer_args breaks deepstate-afl

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#368]
Compare:

```
> deepstate-afl ./testcblosc_AFL -o fuzz_afl
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
INFO:deepstate.core.base:Setting log level from --min_log_level: 2
INFO:deepstate.core.fuzz:Calling pre_exec before fuzzing
INFO:deepstate.core.fuzz:Creating fake input seed file in directory `/tmp/deepstate_fake_seedfri6uubv`
INFO:deepstate.core.fuzz:Executing command `['/home/user/deps/afl/afl-fuzz', '-o', 'fuzz_afl', '-M', 'the_fuzzer', '-m', '50', '-i', '/tmp/deepstate_fake_seedfri6uubv', '--', '/home/user/deepstate-c-blosc2/testcblosc_AFL', '--input_test_file', '@@', '--abort_on_fail', '--no_fork', '--min_log_level', '2']`
INFO:deepstate.core.fuzz:Using DeepState output.
INFO:deepstate.core.fuzz:Started fuzzer process with PID 710.
FUZZ_STATS:deepstate.core.fuzz:unique_crashes:0
FUZZ_STATS:deepstate.core.fuzz:fuzzer_pid:710
FUZZ_STATS:deepstate.core.fuzz:start_time:1613321221
FUZZ_STATS:deepstate.core.fuzz:execs_done:8
FUZZ_STATS:deepstate.core.fuzz:execs_per_sec:15.53
```

```
> deepstate-afl ./testcblosc_AFL -o fuzz_afl --fuzzer_args d
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
INFO:deepstate.core.base:Setting log level from --min_log_level: 2
INFO:deepstate.core.fuzz:Calling pre_exec before fuzzing
INFO:deepstate.core.fuzz:Creating fake input seed file in directory `/tmp/deepstate_fake_seedisgnyclv`
INFO:deepstate.core.fuzz:Executing command `['/home/user/deps/afl/afl-fuzz', '-o', 'fuzz_afl', '-M', 'the_fuzzer', '-m', '50', '-d', '-i', '/tmp/deepstate_fake_seedisgnyclv', '--', '/home/user/deepstate-c-blosc2/testcblosc_AFL', '--input_test_file', '@@', '--abort_on_fail', '--no_fork', '--min_log_level', '2']`
INFO:deepstate.core.fuzz:Using DeepState output.
INFO:deepstate.core.fuzz:Started fuzzer process with PID 1085.
ERROR:deepstate.core.fuzz:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/fuzz.py", line 730, in run
    raise FuzzFrontendError(f"Fuzzer {self.name} (PID {self.proc.pid}) exited "
deepstate.core.fuzz.FuzzFrontendError: Fuzzer AFL (PID 1085) exited with return code 1.

ERROR:deepstate.core.fuzz:Exception during fuzzer AFL run.
ERROR:deepstate.core.fuzz:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/fuzz.py", line 758, in run
    self.manage()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/fuzz.py", line 588, in manage
    self.populate_stats()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/fuzz/afl.py", line 147, in populate_stats
    super().populate_stats()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/fuzz.py", line 834, in populate_stats
    crashes: int = len(os.listdir(self.crash_dir))
FileNotFoundError: [Errno 2] No such file or directory: 'fuzz_afl/the_fuzzer/crashes'

ERROR:deepstate.core.fuzz:Exception during fuzzer AFL run.
INFO:deepstate.core.fuzz:Killing process 1085 and childs.
INFO:deepstate.core.fuzz:Fuzzer exec time: 1.41s
INFO:deepstate.core.fuzz:Calling post-exec for fuzzer post-processing
```

The constructed args look ok, so it's something more subtle than that, I think.  Pretty annoying, since providing -d is likely to be fairly standard practice!

**Comment by agroce** [comment]
@GrosQuildu any idea what's going on here?  Looking for fuzzer_args in fuzz.py and afl.py nothing was obviously wrong.  The added -d is the only change I see in the command line, too.  Something else parsed wrong/not run?

I believe I noticed some time back fuzzer_args doesn't work for ilbFuzzer, either.

**Comment by agroce** [comment]
(Probably not just AFL, will confirm libfuzzer tomorrow)

**Comment by agroce** [comment]
Aha.  I think this is actually an issue of -S implying -d and it breaking.  Ok, never mind!  And libfuzzer was the whole libfuzzer output problem.
