### ISSUE TITLE
The ensembler seems to be broken:

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#377]
On latest docker:

```
user@95f3fb5202bd:~/testfs$ deepstate-ensembler --help
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-ensembler", line 33, in <module>
    sys.exit(load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-ensembler')())
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/auxiliary/ensembler.py", line 368, in main
    ensembler = Ensembler()
TypeError: __init__() missing 1 required positional argument: 'envvar'
```

**Comment by agroce** [comment]
@ex0dus-0x any idea of how to quickly fix this, if the code is significantly out of date, or just needs a little tweak?  I've never inspected it/used it except once or twice

**Comment by agroce** [comment]
@GrosQuildu looks like you last touched this -- there are multiple broken things, here, I tried  fixing a few but ran into general issues with the directories not being set, parameters to fuzzer object missing, etc.  Any chance you could take a look and see if you can fix it?

**Comment by GrosQuildu** [comment]
Will try.

**Comment by agroce** [comment]
Thanks!  Are you interested in joining the DeepState tool paper for ISSTA?

**Comment by agroce** [comment]
@GrosQuildu are you interested in joining the ISSTA demo paper?
