### ISSUE TITLE
Rare crash in DeepState_Setup

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#393]
```
user@713d2d6e3f90:~/deepstate-stack$ clang++ -o stack -ldeepstate -fsanitize=address
user@713d2d6e3f90:~/deepstate-stack$ ./stack
AddressSanitizer:DEADLYSIGNAL
=================================================================
==45==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004c9247 bp 0x000000000001 sp 0x7ffed5a8d940 T0)
==45==The signal is caused by a READ memory access.
==45==Hint: address points to the zero page.
    #0 0x4c9246 in DeepState_Setup (/home/user/deepstate-stack/stack+0x4c9246)
    #1 0x4ca4ba in main (/home/user/deepstate-stack/stack+0x4ca4ba)
    #2 0x7f473a01dbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #3 0x41b6e9 in _start (/home/user/deepstate-stack/stack+0x41b6e9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/user/deepstate-stack/stack+0x4c9246) in DeepState_Setup
==45==ABORTING
```

Using the code at https://github.com/agroce/deepstate-stack, in a fresh start of a docker container.  Same steps after restarting the container did not produce this.  Presumably some non-determinism/UB in Setup, but not obvious where.

**Comment by agroce** [comment]
The issue turns out to be that DeepState compiles to an executable that crashes if you forget to include the harness file.

> clang++ -o stack -ldeepstate

will do the trick.  Oops.  Long term, adding a polite warning about that would be a good idea.
