### ISSUE TITLE
`--num_workers` argument not being detected

### ISSUE THREAD

**Issue by Anirban166** [trailofbits/deepstate#396]
I'm trying to run the pre-built examples in DeepState with AFL installed, but when I try to run, the `num_workers` fuzzer argument seems to be unrecognized:
```sh
(venv) <username>@<systemname> deepstate % deepstate-afl --num_workers 4 --output_test_dir out ./build/examples/IntegerOverflow
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
usage: deepstate-afl [-h] [-i INPUT_SEEDS] [-s MAX_INPUT_SIZE]
                     [--dictionary DICTIONARY] [--exec_timeout EXEC_TIMEOUT]
                     [--blackbox] [--fuzzer_out]
                     [--fuzzer_args [FUZZER_ARGS ...]] [--sync_dir SYNC_DIR]
                     [--sync_cycle SYNC_CYCLE] [--fuzzer_help]
                     [--home_path HOME_PATH] [-o OUTPUT_TEST_DIR] [-c CONFIG]
                     [-t TIMEOUT] [--mem_limit MEM_LIMIT]
                     [--min_log_level MIN_LOG_LEVEL] [--which_test WHICH_TEST]
                     [--target_args [TARGET_ARGS ...]]
                     [binary]
deepstate-afl: error: unrecognized arguments: --num_workers ./build/examples/IntegerOverflow
```
Omitting `--num_workers` raises another error: (similar to #368)
```sh
(venv) <username>@<systemname> deepstate % deepstate-afl --output_test_dir out ./build/examples/IntegerOverflow
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
INFO:deepstate.core.base:Setting log level from --min_log_level: 2
INFO:deepstate.core.fuzz:Calling pre_exec before fuzzing
INFO:deepstate.executors.fuzz.afl:Resuming fuzzing using seeds from out/the_fuzzer/queue (skipping --input_seeds option).
INFO:deepstate.core.fuzz:Executing command `['/usr/local/bin/afl-fuzz', '-o', 'out', '-M', 'the_fuzzer', '-m', '50', '-i', '-', '--', '/Users/<username>/deepstate/build/examples/IntegerOverflow', '--input_stdin', '--abort_on_fail', '--no_fork', '--min_log_level', '2']`
INFO:deepstate.core.fuzz:Using DeepState output.
INFO:deepstate.core.fuzz:Started fuzzer process with PID 89285.
ERROR:deepstate.core.fuzz:Traceback (most recent call last):
  File "/Users/<username>/deepstate/venv/lib/python3.9/site-packages/deepstate-0.1-py3.9.egg/deepstate/core/fuzz.py", line 732, in run
    raise FuzzFrontendError(f"Fuzzer {self.name} (PID {self.proc.pid}) exited "
deepstate.core.fuzz.FuzzFrontendError: Fuzzer AFL (PID 89285) exited with return code 1.

ERROR:deepstate.core.fuzz:Exception during fuzzer AFL run.
FUZZ_STATS:deepstate.core.fuzz:unique_crashes:0
FUZZ_STATS:deepstate.core.fuzz:fuzzer_pid:89285
FUZZ_STATS:deepstate.core.fuzz:start_time:1658335236
FUZZ_STATS:deepstate.core.fuzz:------------------------------
INFO:deepstate.core.fuzz:Killing process 89285 and childs.
INFO:deepstate.core.fuzz:Fuzzer exec time: 1.77s
INFO:deepstate.core.fuzz:Calling post-exec for fuzzer post-processing
```

Probably worth mentioning, or just for reference: I'm running DeepState on the native environment of an OS X machine, and not on a Docker container or other isolated environments like WSL.

**Comment by Anirban166** [comment]
I'm wondering what are the possible scenarios in which a fuzzer or DeepState itself would fail, leaving a return code of 1 (since the conditional logic branches to the else part in and raises [this](https://github.com/trailofbits/deepstate/blob/c055beeeff11eefde5cbd40d266cbc3870a2e963/bin/deepstate/core/fuzz.py#L732))

**Comment by Anirban166** [comment]
I'm wondering what are the possible scenarios in which a fuzzer or DeepState itself would fail, leaving a return code of 1 (since the conditional logic branches to the else part and raises [this](https://github.com/trailofbits/deepstate/blob/c055beeeff11eefde5cbd40d266cbc3870a2e963/bin/deepstate/core/fuzz.py#L732))

**Comment by agroce** [comment]
Run this with `--fuzzer-out` so we can see the actual AFL failure?

**Comment by agroce** [comment]
it looks to me like --num-workers just isn't an expected argument to deepstate-afl?  I'm not sure the deepstate-afl executor is set up to start and coordinate parallel fuzzer instances...  does the documentation say --num-workers is available for it somewhere?

**Comment by Anirban166** [comment]
> Run this with `--fuzzer-out` so we can see the actual AFL failure?

```sh
deepstate-afl ./IntegerOverflow_AFL --fuzzer_out --fuzzer_args d --output_test_dir output 
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
INFO:deepstate.core.base:Setting log level from --min_log_level: 2
INFO:deepstate.core.fuzz:Calling pre_exec before fuzzing
INFO:deepstate.core.fuzz:Creating fake input seed file in directory `/tmp/deepstate_fake_seed1mm7dzv2`
INFO:deepstate.core.fuzz:Executing command `['/home/user/deps/afl/afl-fuzz', '-o', 'output', '-m', '50', '-S', 'the_fuzzer', '-i', '/tmp/deepstate_fake_seed1mm7dzv2', '--', '/home/user/deepstate/build_afl/examples/IntegerOverflow_AFL', '--input_stdin', '--abort_on_fail', '--no_fork', '--min_log_level', '2']`
INFO:deepstate.core.fuzz:Using fuzzer output.
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 8 CPU cores and 1 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Setting up output directories...
[*] Scanning '/tmp/deepstate_fake_seed1mm7dzv2'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:fake_seed'...
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-] Oops, the program crashed with one of the test cases provided. There are
    several possible explanations:

    - The test case causes known crashes under normal working conditions. If
      so, please remove it. The fuzzer should be seeded with interesting
      inputs - but not ones that cause an outright crash.

    - The current memory limit (50.0 MB) is too low for this program, causing
      it to die due to OOM when parsing valid files. To fix this, try
      bumping it up with the -m setting in the command line. If in doubt,
      try something along the lines of:

      ( ulimit -Sv $[49 << 10]; /path/to/binary [...] <testcase )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary. Also,
      if you are using ASAN, see /usr/local/share/doc/afl/notes_for_asan.txt.

    - Least likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Test case 'id:000000,orig:fake_seed' results in a crash
         Location : perform_dry_run(), afl-fuzz.c:2852

ERROR:deepstate.core.fuzz:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/core/fuzz.py", line 729, in run
    raise FuzzFrontendError(f"Fuzzer {self.name} (PID {self.proc.pid}) exited "
deepstate.core.fuzz.FuzzFrontendError: Fuzzer AFL (PID 129) exited with return code 1.

ERROR:deepstate.core.fuzz:Exception during fuzzer AFL run.
INFO:deepstate.core.fuzz:Fuzzer exec time: 1.48s
INFO:deepstate.core.fuzz:Calling post-exec for fuzzer post-processing
```

**Comment by Anirban166** [comment]
> it looks to me like --num-workers just isn't an expected argument to deepstate-afl? I'm not sure the deepstate-afl executor is set up to start and coordinate parallel fuzzer instances... does the documentation say --num-workers is available for it somewhere?

You're right, I just realized that is specific to angr, and *none* of the fuzzers (tried with libfuzzer and honggfuzz as well) seem to have that as an argument!
It's working fine or as expected on angr so I'll close this, but the non-deterministic exit might be an actual issue - will plug in more details in a separate thread (given the title here is just focused on that argument-specific issue) after lunch. Thanks for your help!

**Comment by agroce** [comment]
The failure with `./IntegerOverflow_AFL` isn't a bug -- it's just that the default seed file DeepState uses triggers a crash (it's not hard to find crashes for this) and AFL doesn't like any input seeds you provide to cause a crash.  You'd need to provide your own seeds or something for this example.  If you see that happening only sometimes, now, that would be interesting, but it happens 100% of the time for me for that example.
