### ISSUE TITLE
Fix Manticore python version problem in Docker

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#399]
```
#5 19.93  Downloading https://files.pythonhosted.org/packages/6c/be/4e32d02bf08b8f76bf6e59f2a531690c1e4264530404501f3489ca975d9a/protobuf-4.21.0-py2.py3-none-any.whl (164kB)
#5 20.00 protobuf requires Python '>=3.7' but the running Python is 3.6.9
```

This prevents just doing a pip install manticore; can be fixed by modifying base to use a newer Python 3, should not be a big deal

**Comment by agroce** [comment]
Tried to fix in branch https://github.com/trailofbits/deepstate/tree/fix_manticore but ran into the issue that the needed python version switch hoses all the installs:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 564, in from_name
    return next(cls.discover(name=name))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/deepstate", line 33, in <module>
    sys.exit(load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate')())
  File "/usr/bin/deepstate", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/user/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 988, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/user/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 566, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for deepstate
```

Docker builds fine, but the executors don't work.
