### ISSUE TITLE
Range conversions can crash reducer

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#401]
```
user@23eac9faf0ae:~/fuzz_tcas$ deepstate-reduce ./TCAS fail.test small.test --verbose
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
Original test has 40 bytes
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-reduce", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-reduce')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/auxiliary/reducer.py", line 281, in main
    fixRangeConversions(currentTest, rangeConversions(initial))
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/auxiliary/reducer.py", line 264, in fixRangeConversions
    test[pos[1]] = value
ValueError: byte must be in range(0, 256)
```

**Comment by agroce** [comment]
Fixed in https://github.com/trailofbits/deepstate/commit/ad0f4ed766d79fc8438887c870f2a464a842ce3d
