### ISSUE TITLE
angr and manticore seem to fail the StreamingAndFormatting test

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/deepstate#74]
angr error:

```
ERROR   | 2018-07-19 12:12:06,465 | deepstate.angr | Uncaught exception: unsupported format character 'p' (0x70) at index 1
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 305, in run_test
    do_run_test(project, test, apis, run_state, should_call_state)
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 295, in do_run_test
    DeepAngr(state=state).report()
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 376, in report
    logger(self._stream_to_message(stream))
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 320, in _stream_to_message
    message.append(format_str % val)
ValueError: unsupported format character 'p' (0x70) at index 1
```

manticore error:

```
INFO:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(29): 97
INFO:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(30): 1
INFO:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(31): 1.000000
INFO:deepstate:/home/travis/build/trailofbits/deepstate/examples/StreamingAndFormatting.cpp(32): string
2018-07-19 12:12:30,812: [7679] m.c.executor:ERROR: Exception: unsupported format character 'p' (0x70) at index 1
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/manticore-0.1.10-py2.7.egg/manticore/core/executor.py", line 479, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/deepstate/main_manticore.py", line 306, in done_test
    mc.report()
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 376, in report
    logger(self._stream_to_message(stream))
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 320, in _stream_to_message
    message.append(format_str % val)
ValueError: unsupported format character 'p' (0x70) at index 1
```

and the full log is here:
https://travis-ci.org/trailofbits/deepstate/jobs/405771433

**Comment by pgoodman** [comment]
Ah this is simple, we should handle the `p` as `0x%x` in Python. It should probably be handled on the C side, though.

**Comment by agroce** [comment]
Ah, yes, I skipped flagging that since it's a known and probably easy but low priority issue:  #34
